language: node_js
node_js: node
cache: yarn

script:
  - yarn
  - yarn build
  - zip -r floodlabel-client.zip build

# Deploy uploads the zipfile to https://artifacts.lizard.net
deploy:
  # Master builds end up on https://floodlabel.net/
  - provider: script
    skip_cleanup: true
    script: bash upload-artifact.sh production
    on:
      branch: master

notifications:
  email: false
